WebApplication1/WebApplication1/Controllers/SocialController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Areas.Identity.Data;
using WebApplication1.Data;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class SocialController : Controller
    {

        private readonly WebApplication1Context _context;
        private readonly UserManager<User> _userManager;

        public SocialController(WebApplication1Context context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        /// <summary>
        /// Função para mostrar publicações da página inicial do user e de pessoas que ele segue
        /// </summary>
        /// <returns>Retorna a página inicial coma s publicações</returns>
        public async Task<IActionResult> PaginaSocial()
        {
            var curUser = _userManager.GetUserAsync(User).Result;
            //var curUser = _userManager.FindByIdAsync(id).Result;
            var posts = _context.FeedPosts.ToList();


            var following = _context.Followers.Where(f => curUser.Id.Equals(f.UserIdThatFollows)).ToList();

            var postsFeed = new HashSet<FeedPost>();
            var curPosts = new List<FeedPost>();

            foreach (var myPosts in posts)
            {
                if (myPosts.UserId.Equals(curUser.Id))
                {
                    curPosts.Add(myPosts);
                }
            }

            postsFeed.UnionWith(curPosts);

            foreach (var allposts in posts)
            {
               foreach(var followinPosts in following)
                {
                    if(allposts.UserId.Equals(followinPosts.UserIdFollowed))
                    {
                        postsFeed.Add(allposts);
                    }
                }
            }

            return View(postsFeed);
        }

        /// <summary>
        /// Função para adicionar um post há página
        /// </summary>
        /// <param name="id">Id do user</param>
        /// <param name="text">texto do post</param>
        /// <returns>Retorna página de publicações atualizada com o post novo</returns>
        [HttpPost]
        public async Task<IActionResult> AddPost(string id, string text)
        {
            //var user = _userManager.FindByIdAsync(id).Result;
            var user = _context.Users.FirstOrDefault(u => u.Id == id);
            var post = new FeedPost
            {
                UserId = id,
                User = user,
                Post = text,
            };

            _context.FeedPosts.AddAsync(post);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(PaginaSocial), new { id = user.Id });
        }

        /// <summary>
        /// Função para apagar um post(publicação)
        /// </summary>
        /// <param name="id">Id do post</param>
        /// <returns>Retorna Página de publicações atualizada sem o post</returns>
        public async Task<IActionResult> DeletePost(int? id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }
                var post = _context.FeedPosts.FirstOrDefault(e => e.Id == id);
                _context.FeedPosts.Remove(post);
                await _context.SaveChangesAsync();
                TempData["SuccessoPost"] = "Publicação apagada com sucesso";
                return RedirectToAction(nameof(PaginaSocial));
            }catch
            {
                TempData["ErroPost"] = "Não foi possivel apagar publicação";
                return RedirectToAction(nameof(PaginaSocial));
            }
               
        }

        /// <summary>
        /// Função para Seguir users que aparecam na página de publicações
        /// </summary>
        /// <param name="id">id do user</param>
        /// <returns>Retorna página de publicações com o user seguido no lugar das pessoas que segue</returns>
        [HttpPost]
        public async Task<IActionResult> FollowUserSocialFeed(string? followedId, string? curUserId)
        {
            var followers = _context.Followers.Where(u => u.UserIdFollowed == followedId).ToList();
            if (followedId == null)
            {
                return NotFound();
            }
            var user = _context.Users.FirstOrDefault(u => u.Id == followedId);
            if (user == null)
            {
                return NotFound();
            }
            var curUser = _context.Users.FirstOrDefault(u => u.Id == curUserId);
            foreach (var followed in followers)
            {
                if (followed.UserIdFollowed.Equals(user.Id))
                {
                    user.Followers.Add(_context.Users.FirstOrDefault(u => u.Id == followed.UserIdThatFollows));
                    //_userManager.FindByIdAsync(followed.UserIdThatFollows).Result);
                }
            }
            user.Followers.Add(curUser);
            var socialInsert = new SocialModel
            {
                UserIdFollowed = user.Id,
                UserIdThatFollows = curUser.Id
            };
            _context.Followers.Add(socialInsert);
            await _context.SaveChangesAsync();

            var counterFollowings = _context.Followers.Where(u => curUser.Id == u.UserIdThatFollows).ToList().Count();
            var counterFollowers = _context.Followers.Where(u => user.Id == u.UserIdFollowed).ToList().Count();
            var conqFollowingFlag = false;
            var conqFollowersFlag = false;
            if (counterFollowers == 5)
            {
                foreach (var conq in _context.ConquistasUser.ToList())
                {
                    if (conq.UserId.Equals(user.Id))
                    {
                        if (conq.ConquistId == 2)
                        {
                            conqFollowersFlag = true;
                        }
                    }
                }
                if (!conqFollowersFlag)
                {
                    var novaCOnquista = new ConquistaUser
                    {
                        UserId = user.Id,
                        ConquistId = 2,
                        DateAchieved = DateTime.Now,
                    };
                    _context.ConquistasUser.Add(novaCOnquista);
                }
            }
            await _context.SaveChangesAsync();
            if (counterFollowings == 5)
            {
                foreach (var conq in _context.ConquistasUser.ToList())
                {
                    if (conq.UserId.Equals(curUser.Id))
                    {
                        if (conq.ConquistId == 3)
                        {
                            conqFollowingFlag = true;
                        }
                    }
                }
                if (!conqFollowingFlag)
                {
                    var novaCOnquista = new ConquistaUser
                    {
                        UserId = curUser.Id,
                        ConquistId = 3,
                        DateAchieved = DateTime.Now,
                    };
                    _context.ConquistasUser.Add(novaCOnquista);
                }
            }
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(PaginaSocial));
        }

        /// <summary>
        /// Função para deixar de seguir um user na página de publicações
        /// </summary>
        /// <param name="id">Id do user</param>
        /// <returns>Retorna página de publicações com o user seguido no lugar das pessoas que não segue</returns>
        [HttpPost]
        public async Task<IActionResult> UnfollowUserSocialFeed(string? followedId, string? curUserId)
        {
            var followers = _context.Followers.Where(u => u.UserIdFollowed == followedId).ToList();
            if (followedId == null)
            {
                return NotFound();
            }
            var user = _context.Users.FirstOrDefault(u => u.Id == followedId);
            if (user == null)
            {
                return NotFound();
            }
            foreach (var followed in followers)
            {
                if (followed.UserIdFollowed.Equals(user.Id))
                {
                    user.Followers.Add(_context.Users.FirstOrDefault(u => u.Id == followed.UserIdThatFollows));
                }
            }
            var curUser = _context.Users.FirstOrDefault(u => u.Id == curUserId);
            foreach (var f in followers)
            {
                if (f.UserIdThatFollows.Equals(curUser.Id) && f.UserIdFollowed.Equals(user.Id))
                {
                    user.Followers.Remove(curUser);
                    _context.Followers.Remove(f);
                }
            }
            _context.SaveChanges();
            return RedirectToAction(nameof(PaginaSocial));
        }
    }
}

WebApplication1/WebApplication1/Views/Social/PaginaSocial.cshtml
@using Microsoft.AspNetCore.Identity
@using WebApplication1.Areas.Identity.Data
@using WebApplication1.Data
@using WebApplication1.Models

@model IEnumerable<FeedPost>;
@inject UserManager<User> _userManager;
@inject WebApplication1Context _context;
@{
    ViewData["Title"] = "Feed do Utilizador";
    var users = _context.Users.ToList();
    var eventos = _context.eventos.ToList();
    var curUser = _userManager.GetUserAsync(User).Result;
    var following = _context.Followers.Where(u => curUser.Id.Equals(u.UserIdThatFollows)).ToList();
    var followingUserList = new List<User>();
    var notFollowing = new List<User>();
    foreach (var f in following)
    {
        followingUserList.Add(_userManager.FindByIdAsync(f.UserIdFollowed).Result);
    }

    if (following.Count() == 0)
    {
        notFollowing.AddRange(users.Where(u => !u.Id.Equals(curUser.Id)).ToList());
    }
    else
    {
        foreach (var user in users)
        {
            if (!user.Id.Equals(curUser.Id) && !followingUserList.Contains(user))
            {
                notFollowing.Add(user);
            }
        }
    }
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" />
</head>
<style>
    body {
        background-color: #e2e8f0;
    }

    .container {
        max-width: 95%;
    }

    .right {
        float: right;
        margin-right: 5px;
    }

    .azul {
        background-color: #084d6e;
        color: white;
    }

    ::-webkit-scrollbar {
        width: 8px;
        height: 12px;
    }

    ::-webkit-scrollbar-track {
        background: #f5f5f5;
        border-radius: 10px;
    }

    ::-webkit-scrollbar-thumb {
        border-radius: 10px;
        background: #ccc;
    }

        ::-webkit-scrollbar-thumb:hover {
            background: #084d6e;
        }

    .hovertext {
        position: relative;
    }

        .hovertext:before {
            content: attr(data-hover);
            visibility: hidden;
            opacity: 0;
            width: 350px;
            background-color: #cfcfcf;
            color: black;
            text-align: center;
            border-radius: 5px;
            padding: 5px 0;
            transition: opacity 1s ease-in-out;
            position: absolute;
            z-index: 1;
            left: 0;
            top: 110%;
        }

        .hovertext:hover:before {
            opacity: 1;
            visibility: visible;
        }

    .perfilNome {
        color: black;
    }

    .rounded-circle {
        width: 50px;
        height: 50px;
        object-fit: cover;
    }

    

</style>
<body>
    @if (TempData["ErroPost"] != null)
    {
        <div class="alert alert-danger">
            <strong>Erro!</strong> Não foi possivel apagar publicação
        </div>
    }
    @if (TempData["SuccessoPost"] != null)
    {
        <div class="alert alert-success">
            <strong>Successo!</strong> Publicação apagada com sucesso
        </div>
    }
    <div class="container">
        <span class="hovertext" data-hover="Nesta página, pode ficar a conhecer algumas das publicações das pessoas que está a seguir. Pode também fazer uma publicação, para isso basta escrever na caixa 'Publicação', e clicar em 'Publicar', e de seguida todos os seus seguidores poderão ver a sua publicação. Tem a oportunidade de seguir pessoas que ainda não segue, para isso basta consultar 'Talvez queira seguir'.">
            <img src="~/imagens/help-web-button.png" width="35" />
        </span>
        <div class="text-center">
            <h1 class="display-4">Social Feed</h1>
        </div>
        <hr style="height:2px;">
        <div class="row" style="margin-top: 30px;">
            <div class="col-sm-0 col-md-0 col-lg-0"></div>
            <div class="col-sm- col-md- col-lg-7">
                <b><p style="color: gray;">O seu Feed</p></b>
                @foreach (var posts in Model)
                {
                    @*FOREACH DOS MEUS POSTS E DAS PESSOAS QUE EU SIGO*@
                    <div class="row" style="margin-top:30px">
                        <div class="card shadow-sm">
                            <div class="card-body">
                                <div clas="row">
                                    <div class="col-sm-12 col-md-12 col-lg-12">
                                        <p style="height: auto;">
                                            <img src="~/uploads/@posts.User.ImagePath" onerror="https://bootdey.com/img/Content/avatar/avatar7.png" alt="ProfilePic" class="rounded-circle" style="margin-right: 5px;" width="50" height="50">
                                            <b>@posts.User.Name</b>
                                        </p>
                                        <hr>
                                        <div>
                                            <p>@posts.Post</p>

                                            @if (posts.UserId == @_userManager.GetUserAsync(User).Result.Id || @_userManager.GetUserAsync(User).Result.isAdmin == true)
                                            {
                                                @*SO APARECER BOTAO DE APAGAR SE FUI EU A FAZER POST*@
                                                <a id="delete" asp-action="DeletePost" asp-route-id="@posts.Id" asp-route-curId="@_userManager.GetUserAsync(User).Result.Id" class="btn btn-danger right">Apagar</a>
                                                @*SO APARECER BOTAO DE APAGAR SE FUI EU A FAZER POST*@
                                            }
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    @*FOREACH DOS MEUS POSTS E DAS PESSOAS QUE EU SIGO*@
                }
            </div>
            <div class="col-sm-0 col-md-0 col-lg-2"></div>
            <div class="col-sm- col-md- col-lg- col-xl-3">
                <form id="criarpublicacao" method="post">
                    <div class="row">
                        <div class="card shadow-sm" style="min-width: 360.250px">
                            <div class="card-body">
                                <p style="text-align: center;">
                                    <b>PUBLICAÇÃO</b>
                                </p>
                                <hr>
                                <textarea name="text" class="form-control" style="height:150px; resize: none;" id="publicacao"></textarea>
                                <span class="error"><p id="publicacao_error" style="color:red"></p></span>
                                <input name="id" value="@_userManager.GetUserAsync(User).Result.Id" hidden />
                                <br>
                                @*BOTAO PARA ADICIONAR POST*@
                                <button asp-action="AddPost" type="submit" class="btn btn-primary right azul">Publicar</button>
                            </div>
                        </div>
                    </div>
                </form>
                <br>
                <div class="row">
                    <div class="card shadow-sm" style="min-width: 360.250px; overflow: auto; height:14rem;">
                        <div class="card-body">
                            <p style="text-align: center;">
                                <b>A SEGUIR</b>
                            </p>
                            <hr>
                            @*FOREACH DAS PESSOAS QUE EU SIGO*@
                            @foreach (var user in followingUserList)
                            {
                                if (user.isActive)
                                {
                                    <div class="input-group">
                                        <div class="form-outline" style="display:flex; flex-direction:row">
                                            <img class="rounded-circle" src="/uploads/@user.ImagePath" onerror="this.src='https://bootdey.com/img/Content/avatar/avatar7.png'" class="rounded-circle" style="margin-right: 5px;" width="50" height="50">
                                            <b class="nome-pessoa">@user.Name</b>&nbsp;&nbsp;
                                            <form method="post">
                                                <input name="followedId" hidden value="@user.Id" />
                                                <input name="curUserId" hidden value="@curUser.Id" />
                                                <button type="submit" class="btn btn-danger right" style="color:white; font-size: 8px" asp-controller="Social" asp-action="UnfollowUserSocialFeed">Deixar de Seguir</button>
                                            </form>
                                        </div>
                                    </div>
                                    <br>
                                }
                            }
                            @*FOREACH DAS PESSOAS QUE EU SIGO*@
                        </div>
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="card-descobrir card shadow-sm" style="min-width: 360.250px; overflow: auto; height:14rem;">
                        <div class="card-body">
                            <p style="text-align: center;">
                                <b>TALVEZ QUEIRA SEGUIR</b>
                            </p>
                            <hr>
                            @*FOREACH DAS PESSOAS QUE EU NAO SIGO*@
                            @{
                                var counter = 0;
                            }
                            @foreach (var userNotfollowed in notFollowing)
                            {
                                if (!userNotfollowed.isAdmin)
                                {
                                    if (userNotfollowed.isActive)
                                    {
                                        if (counter < 5)
                                        {
                                            <div class="input-group">
                                                <div class="form-outline" style="display:flex; flex-direction:row">
                                                    <img class="rounded-circle" src="/uploads/@userNotfollowed.ImagePath" onerror="this.src='https://bootdey.com/img/Content/avatar/avatar7.png'" class="rounded-circle" style="margin-right: 5px;" width="30" height="30">
                                                    @*<b class="nome-pessoa">@userNotfollowed.Name</b>&nbsp;&nbsp;*@
                                                    <a asp-controller="Utilizador" asp-action="PaginaPerfilUtilizador" asp-route-id=@userNotfollowed.Id class="perfilNome">@userNotfollowed.Name</a>&nbsp;&nbsp;
                                                    <form method="post">
                                                        <input name="followedId" hidden value="@userNotfollowed.Id" />
                                                        <input name="curUserId" hidden value="@curUser.Id" />
                                                        <button type="submit" class="btn btn-info seguir" style="color:white; font-size: 8px; background-color: #084d6e;" asp-controller="Social" asp-action="FollowUserSocialFeed">Seguir</button>
                                                    </form>
                                                </div>
                                            </div>
                                            <br>
                                            counter++;
                                        }
                                    }
                                }
                            }
                            @*FOREACH DAS PESSOAS QUE EU NAO SIGO*@
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
</body>

@section Scripts {

<script>

    document.getElementById("criarpublicacao").onsubmit = function () {
        var x = document.forms["criarpublicacao"]["publicacao"].value;

        var submit = true;

        if (x == null || x == "") {
            publicacao_error = "* É preciso escrever alguma publicação *";
            document.getElementById("publicacao_error").innerHTML = publicacao_error;

            submit = false;
        }

        return submit;
    }

    function removeWarning() {
        document.getElementById(this.id + "_error").innerHTML = "";
    }

    document.getElementById("publicacao").onkeyup = removeWarning;



</script>
}
</html>