WebApplication1/WebApplication1/Controllers/EventoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Areas.Identity.Data;
using WebApplication1.Data;
using WebApplication1.Infrastructure;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class EventoController : Controller
    {
        private readonly WebApplication1Context _context;
        private readonly UserManager<User> _userManager;
        private readonly IUnitOfWork _unitOfWork;
        protected IEmailSender _emailSender;
        public EventoController(WebApplication1Context context, UserManager<User> userManager, IUnitOfWork unitOfWork, IEmailSender emailSender)
        {
            _context = context;
            _userManager = userManager;
            _unitOfWork = unitOfWork;
            _emailSender = emailSender;
        }
        public async Task<IActionResult> CriarEvento()
        {
            return View();
        }

        /// <summary>
        /// Funçao que permite ao utilizador ver os seus eventos e das pessoas que segue
        /// </summary>
        /// <returns>retorna todos os eventos dele + seguidores</returns>
        [HttpGet]
        public IActionResult InicialEventos()
        {
            var curUser = _userManager.GetUserAsync(User).Result;
            if (curUser == null)
            {
                return NotFound();
            }
            var eventos = _context.eventos.ToList();
            var following = _context.Followers.Where(f => curUser.Id.Equals(f.UserIdThatFollows)).ToList();
            var userEventos = _context.UserEventos.ToList();
            var eventFeed = new HashSet<EventoModel>();
            var curUserInEvents = new List<EventoModel>();
            foreach (var evento in eventos)
            {
                foreach (var userEvento in userEventos)
                {

                    if (userEvento.EventoId == evento.Id && userEvento.UserId.Equals(curUser.Id))
                    {
                        curUserInEvents.Add(evento);
                    }
                }
                continue;
            }
            eventFeed.UnionWith(curUserInEvents);
            foreach (var evento in eventos)
            {
                foreach (var userEvento in userEventos)
                {
                    foreach (var follow in following)
                    {
                        if (userEvento.EventoId == evento.Id && userEvento.UserId.Equals(follow.UserIdFollowed))
                        {
                            eventFeed.Add(evento);
                        }
                    }
                    continue;
                }
            }
            foreach (var evt in eventFeed)
            {
                if (!evt.isActive)
                {
                    eventFeed.Remove(evt);
                }
            }
            ViewData["curUserId"] = curUser.Id;
            return View(eventFeed);
        }

        /// <summary>
        /// Funcao que mostra os eventos do user
        /// </summary>
        /// <returns>retorna todos os seus eventos</returns>
        public IActionResult HistConqEvento()
        {
            var eventos = _context.eventos.ToList();
            return View(eventos);
        }

        /// <summary>
        /// Funcao que permite ver todos os comentarios de um evento
        /// </summary>
        /// <param name="eventoId">Id do evento selecionado</param>
        /// <returns>retorna uma lista de comentarios desse evento</returns>
        public async Task<IActionResult> ComentarioEvento(int eventoId)
        {
            var comentarios = new List<Comentario>();
            foreach (var comment in _context.Comentarios)
            {
                if (comment.EventoId == eventoId)
                {
                    comentarios.Add(comment);
                }
            }
            ViewData["eventoId"] = eventoId;
            return View(comentarios);
        }

        /// <summary>
        /// Função que permite ver fotos de um evento
        /// </summary>
        /// <param name="eventoId">Id de um evento</param>
        /// <returns>retorna uma lista de fotos do evento</returns>
        public IActionResult FotoEvento(int eventoId)
        {
            var fotoList = new List<FotoModel>();
            foreach (var foto in _context.Fotos.ToList())
            {
                if (foto.EventoId == eventoId)
                {
                    fotoList.Add(foto);
                }
            }
            ViewData["eventoId"] = eventoId;
            return View(fotoList);

        }
        /// <summary>
        /// Funcao para criar um evento
        /// </summary>
        /// <param name="evento">Um objeto do tipo evento</param>
        /// <param name="file">um ficheiro para colocar imagem</param>
        /// <returns>retorna uma view para a pagina de eventos com o evento criado</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CriarEvento([Bind("Id, UserLimit, IsPrivate, Description, Name, Location, Date, Country, Sport, IsRecurring, HostUser, UserEventos")] EventoModel evento, IFormFile file, string curUserId)
        {
            try
            {
                var user = _context.Users.FirstOrDefault(u => u.Id.Equals(curUserId));
                var userEvento = new UserEvento
                {
                    User = user,
                    UserId = user.Id,
                    IsHost = true,
                    EventoId = evento.Id,
                    EventoModel = evento,
                };
                evento.HostUser = user;
                evento.UserEventos = new List<UserEvento>();
                evento.UserEventos.Add(userEvento);
                user.UserEventos = new List<UserEvento>();
                user.UserEventos.Add(userEvento);
                // Para o test comentar esta Linha
                _unitOfWork.UploadImage(file);
                if (file != null)
                {
                    evento.ImagePath = file.FileName;
                }
                else
                {
                    evento.ImagePath = "";
                }
                _context.Add(evento);
                await _userManager.UpdateAsync(user);
                await _context.SaveChangesAsync();

                var userEventos = _context.UserEventos.ToList();
                var counter = 0;
                var userConquistas = new List<Conquista>();
                var conquistaFlag = false;
                foreach (var evt in _context.eventos)
                {
                    foreach (var userevento in userEventos)
                    {
                        if (userevento.EventoId == evt.Id)
                        {
                            if (userevento.IsHost && user.Id.Equals(userevento.UserId))
                            {
                                counter++;
                            }
                        }
                    }
                }
                if (counter == 5)
                {
                    var novaCOnquista = new ConquistaUser
                    {
                        UserId = user.Id,
                        ConquistId = 1,
                        DateAchieved = DateTime.Now,
                    };
                    _context.ConquistasUser.Add(novaCOnquista);
                }
                await _context.SaveChangesAsync();
                TempData["SuccessoMensagem"] = "Evento criado com sucesso";
                return RedirectToAction(nameof(VerEvento));
            }
            catch
            {
                TempData["ErroMensagem"] = "Erro ao criar evento";
                return RedirectToAction(nameof(VerEvento));
            }
        }
        public async Task<IActionResult> EditarEvento(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var evento = await _context.eventos.FindAsync(id);
            if (evento != null)
            {
                return View(evento);
            }
            return NotFound();
        }

        /// <summary>
        /// Funcao para editar dados de um evento
        /// </summary>
        /// <param name="id">id do evento</param>
        /// <param name="evento">objeto do tipo evento</param>
        /// <param name="file">file para a imagem</param>
        /// <returns>retorna a pagina de ver os eventos com o evento editado</returns>
        [HttpPost]
        public async Task<IActionResult> EditarEvento(int? id, [Bind("Name, Description, Location, Date, Country, Sport, IsPrivate, IsRecurring, UserLimit")] EventoModel evento, IFormFile file)
        {
            var myEvento = await _context.eventos.FindAsync(id);
            if (myEvento == null) return NotFound();
            if (myEvento.Name != evento.Name)
            {
                myEvento.Name = evento.Name;
            }
            if (myEvento.Description != evento.Description)
            {
                myEvento.Description = evento.Description;
            }
            if (myEvento.Location != evento.Location)
            {
                myEvento.Location = evento.Location;
            }
            if (myEvento.Date != evento.Date)
            {
                myEvento.Date = evento.Date;
            }
            if (myEvento.Country != evento.Country)
            {
                myEvento.Country = evento.Country;
            }
            if (myEvento.Sport != evento.Sport)
            {
                myEvento.Sport = evento.Sport;
            }
            if (myEvento.IsPrivate != evento.IsPrivate)
            {
                myEvento.IsPrivate = evento.IsPrivate;
            }
            if (myEvento.IsRecurring != evento.IsRecurring)
            {
                myEvento.IsRecurring = evento.IsRecurring;
            }

WebApplication1/WebApplication1/Views/Evento/ComentarioEvento.cshtml
@using Microsoft.AspNetCore.Identity
@using WebApplication1.Areas.Identity.Data
@using WebApplication1.Data
@model IEnumerable<Comentario>
@inject UserManager<User> UserManager
@inject WebApplication1Context _context;
@{
    ViewData["Title"] = "Comentarios";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" />
</head>
<style>
    body {
        margin-top: 20px;
        color: #1a202c;
        text-align: left;
        background-color: #e2e8f0;
    }

    .main-body {
        padding: 15px;
    }

    .card {
        box-shadow: 0 1px 3px 0 rgba(0,0,0,.1), 0 1px 2px 0 rgba(0,0,0,.06);
    }

    .card {
        position: relative;
        display: flex;
        flex-direction: column;
        min-width: 0;
        word-wrap: break-word;
        background-color: #fff;
        background-clip: border-box;
        border: 0 solid rgba(0,0,0,.125);
        border-radius: .25rem;
    }

    .card-body {
        flex: 1 1 auto;
        min-height: 1px;
        padding: 1rem;
    }

    .gutters-sm {
        margin-right: -8px;
        margin-left: -8px;
    }

        .gutters-sm > .col, .gutters-sm > [class*=col-] {
            padding-right: 8px;
            padding-left: 8px;
        }

    .mb-3, .my-3 {
        margin-bottom: 1rem !important;
    }

    .bg-gray-300 {
        background-color: #e2e8f0;
    }

    .h-100 {
        height: 100% !important;
    }

    .shadow-none {
        box-shadow: none !important;
    }

    .container {
        max-width: 95%;
    }

    .botao {
        background-color: #084d6e;
        color: white;
    }

    .right {
        float: right;
        margin-right: 5px;
    }

    .rightt {
        float: right;
        margin-right: 5px;
        color: white;
    }

    ::-webkit-scrollbar {
        width: 8px;
        height: 12px;
    }

    ::-webkit-scrollbar-track {
        background: #f5f5f5;
        border-radius: 10px;
    }

    ::-webkit-scrollbar-thumb {
        border-radius: 10px;
        background: #ccc;
    }

        ::-webkit-scrollbar-thumb:hover {
            background: #084d6e;
        }

    .rounded-circle {
        width: 50px;
        height: 50px;
        object-fit: cover;
    }

    .hovertext {
        position: relative;
    }

    .hovertext:before {
        content: attr(data-hover);
        visibility: hidden;
        opacity: 0;
        width: 315px;
        background-color: #cfcfcf;
        color: black;
        text-align: center;
        border-radius: 5px;
        padding: 5px 0;
        transition: opacity 1s ease-in-out;
        position: absolute;
        z-index: 1;
        left: 0;
        top: 110%;
    }

    .hovertext:hover:before {
        opacity: 1;
        visibility: visible;
    }
</style>
<body>
    <div class="container">
        <div class="main-body">         
            <span class="hovertext" data-hover="Nesta página pode fazer vários comentários sobre o evento que está a participar ou participou. Para isso basta escrever o que deseja, e clicar em 'Comentar'. Serão mostrados também outros comentários, feitos por outros utilizadores.">
                <img src="~/imagens/help-web-button.png" width="35" />
            </span>
            <div class="text-center">
                <h1 class="display-4">Comentários</h1>
            </div>
             <hr style="height:2px;">
            <br>
            <div class="row gutters-sm" style="padding-bottom:75px;">
                <div class="col-md-9">
                    <div class="card mb-3">
                        <div class="card-body" style="overflow: auto; height: 638px;">
@*                            <div class="d-flex flex-row-reverse">
                                <a class="btn btn-info botao right" style="color:white;" href='javascript:history.go(-1)'>Voltar</a>
                            </div>*@
                            <div class="row row-cols-1 row-cols-md-3 g-4">
                                @foreach (var comment in @Model)
                                {
                                    <div class="col-md-4 mb-3;">
                                        <div class="card" style="background-color:white; border-radius: 8px; height:125px; overflow: auto; box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2); border: 2px solid #084d6e">
                                            <div class="card-body cartao" style="border-radius: 20px">
                                                <div class="row">
                                                    <div class="col-sm-2">
                                                        <img src="/uploads/@UserManager.FindByIdAsync(comment.UserId).Result.ImagePath" onerror="this.src='https://bootdey.com/img/Content/avatar/avatar7.png'" alt="Admin" class="rounded-circle" width="50">
                                                    </div>
                                                    <div class="col-sm-10">
                                                        <div class="row mt-3">
                                                            <div class="col-md-5">
                                                                <h6 class="mb-0">@UserManager.FindByIdAsync(comment.UserId).Result.Name</h6>
                                                            </div>
                                                        </div>
                                                        <div style="padding:5px"></div>
                                                        <div class="col-sm text-secondary">
                                                            @comment.Comment
                                                        </div>
                                                    </div>
                                                </div>
                                                @if (comment.UserId.Equals(UserManager.GetUserAsync(User).Result.Id))
                                                {
                                                    <form id="apagarComentario" method="Post">
                                                        <input name="comentarioId" hidden value="@comment.Id" />
                                                        <input name="curUserId" hidden value="@UserManager.GetUserAsync(User).Result.Id" />
                                                        <input name="eventoId" hidden value="@ViewData["eventoId"]" />
                                                        <button class="btn btn-danger right" asp-action="ApagarComentario" asp-controller="Evento" type="submit" style="color:white; position:relative; top:-5px">Apagar</button>
                                                    </form>
                                                }
                                            </div>
                                        </div>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 mb-3">
                    <div class="card">
                        <div class="card-body">
                            <form id="Comment" method="post">
                                <input name="eventoId" hidden value="@ViewData["eventoId"]" />
                                <input name="curUserId" hidden value="@UserManager.GetUserAsync(User).Result.Id" />
                                <div class="d-flex flex-column align-items-center text-center">
                                    <textarea name="commentText" class="form-control" style="height:200px; resize: none;" id="comentario"></textarea>
                                </div>
                                 <span class="error"><p id="comentario_error" style="color:red"></p></span>
                                <br>
                                <Button class="btn btn-info botao right" type="Submit" asp-action="ComentarEvento" asp-controller="Evento" style="color:white;">Comentar</Button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

@section Scripts {

<script>

    document.getElementById("Comment").onsubmit = function () {
        var x = document.forms["Comment"]["comentario"].value;

        var submit = true;

        if (x == null || x == "") {
            comentario_error = "* É preciso escrever algum comentário *";
            document.getElementById("comentario_error").innerHTML = comentario_error;
           
            submit = false;
        }

        return submit;
    }

    function removeWarning() {
        document.getElementById(this.id + "_error").innerHTML = "";
    }

    document.getElementById("comentario").onkeyup = removeWarning;



</script>
}



</html>

WebApplication1/WebApplication1/Views/Evento/FotoEvento.cshtml
@using Microsoft.AspNetCore.Identity
@using WebApplication1.Areas.Identity.Data
@using WebApplication1.Data
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<FotoModel>
@inject UserManager<User> UserManager
@inject WebApplication1Context _context;
@{
    ViewData["Title"] = "Fotos do Evento";
    var curUser = UserManager.GetUserAsync(User).Result;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" />
</head>
<style>
    body {
        margin-top: 20px;
        color: #1a202c;
        text-align: left;
        background-color: #e2e8f0;
    }

    .main-body {
        padding: 15px;
    }

    .card {
        box-shadow: 0 1px 3px 0 rgba(0,0,0,.1), 0 1px 2px 0 rgba(0,0,0,.06);
    }

    .card {
        position: relative;
        display: flex;
        flex-direction: column;
        min-width: 0;
        word-wrap: break-word;
        background-color: #fff;
        background-clip: border-box;
        border: 0 solid rgba(0,0,0,.125);
        border-radius: .25rem;
    }

    .card-body {
        flex: 1 1 auto;
        min-height: 1px;
        padding: 1rem;
    }

    .gutters-sm {
        margin-right: -8px;
        margin-left: -8px;
    }

        .gutters-sm > .col, .gutters-sm > [class*=col-] {
            padding-right: 8px;
            padding-left: 8px;
        }

    .mb-3, .my-3 {
        margin-bottom: 1rem !important;
    }

    .bg-gray-300 {
        background-color: #e2e8f0;
    }

    .h-100 {
        height: 100% !important;
    }

    .shadow-none {
        box-shadow: none !important;
    }

    .container {
        max-width: 95%;
    }

    .botao {
        background-color: #084d6e;
        color: white;
    }

    .right {
        float: right;
        margin-right: 5px;
    }

    .rightt {
        float: right;
        margin-right: 5px;
        color: white;
    }

    .posts-content {
        margin-top: 20px;
    }

    .ui-w-40 {
        width: 40px !important;
        height: auto;
    }

    .default-style .ui-bordered {
        border: 1px solid rgba(24,28,33,0.06);
    }

    .ui-bg-cover {
        background-color: transparent;
        background-position: center center;
        background-size: cover;
    }

    .ui-rect {
        padding-top: 50% !important;
    }

    .ui-rect, .ui-rect-30, .ui-rect-60, .ui-rect-67, .ui-rect-75 {
        position: relative !important;
        display: block !important;
        padding-top: 100% !important;
        width: 100% !important;
    }

    .d-flex, .d-inline-flex, .media, .media > :not(.media-body), .jumbotron, .card {
        -ms-flex-negative: 1;
        flex-shrink: 1;
    }

    .bg-dark {
        background-color: rgba(24,28,33,0.9) !important;
    }

    .card-footer, .card hr {
        border-color: rgba(24,28,33,0.06);
    }

    .ui-rect-content {
        position: absolute !important;
        top: 0 !important;
        right: 0 !important;
        bottom: 0 !important;
        left: 0 !important;
    }

    .default-style .ui-bordered {
        border: 1px solid rgba(24,28,33,0.06);
    }

    .botaogaurdar {
        background-color: #084d6e;
        color: white;
    }

    input[type="file"] {
        display: none;
    }

    .rounded-circle {
        width: 50px;
        height: 50px;
        object-fit: cover;
    }

    .hovertext {
        position: relative;
    }

        .hovertext:before {
            content: attr(data-hover);
            visibility: hidden;
            opacity: 0;
            width: 350px;
            background-color: #cfcfcf;
            color: black;
            text-align: center;
            border-radius: 5px;
            padding: 5px 0;
            transition: opacity 1s ease-in-out;
            position: absolute;
            z-index: 1;
            left: 0;
            top: 110%;
        }

        .hovertext:hover:before {
            opacity: 1;
            visibility: visible;
        }
</style>
<body>
    <div class="container">
        <div class="main-body">
            <span class="hovertext" data-hover="Nesta página pode inserir várias fotos sobre o evento, como também ver as fotos colocadas pelos outros participantes do evento. Para colocar uma foto, clique em 'Carregar Foto', e depois de selcionar a foto, clique em 'Adicionar', e verifique que a foto foi colocada com sucesso.">
                <img src="~/imagens/help-web-button.png" width="35" />
            </span>
            <div class="text-center">
                <h1 class="display-4">Fotos</h1>
            </div>
             <hr style="height:2px;">
            <br>
            <div class="row gutters-sm" style="padding-bottom:75px;">
                <div class="col-md-9">
                    <div class="card mb-3">
                        <div class="card-body" style="overflow: auto; height: 638px;">
                            <div class="d-flex flex-row-reverse">
                            </div>
                            <div class="row row-cols-1 row-cols-md-3 g-4">
                                @foreach (var foto in @Model)
                                {
                                    <div class="col-lg-4">
                                        <div class="card mb-4" style="box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);">
                                            <div class="card-body" style="padding-bottom: 0px;">
                                                <div class="media mb-3">
                                                    <img src="/uploads/@UserManager.FindByIdAsync(foto.User).Result.ImagePath" class="rounded-circle" alt="">
                                                    <div class="media-body ml-3">
                                                        @UserManager.FindByIdAsync(foto.User).Result.Name
                                                        <img class="card-img-bottom" src="~/uploads/@foto.ImagePath" alt="Card image cap" style="height:200px; width:215; border-radius:12px">
                                                        <div class="text-muted small">
                                                            <br>
                                                            <form id="ApagarFoto" method="post">
                                                                <input name="fotoId" hidden value="@foto.Id" />
                                                                <input name="eventoId" hidden value="@ViewData["eventoId"]" />
                                                                @if (curUser.Id.Equals(foto.User))
                                                                {
                                                                    <button class="btn btn-danger right" type="submit" asp-action="ApagarFoto" asp-controller="Evento" style="color:white;">Apagar</button>
                                                                }
                                                            </form>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 mb-3">
                    <div class="card">
                        <div class="card-body">
                            <div class="d-flex flex-column align-items-center text-center" id="userPartialView">
                                 <img id="imagem" width="235" height="195" style="border-radius:12px">
                                     <br>
                                <form id="fotoform" method="post" enctype="multipart/form-data">
                                    <label class="btn btn-info botaogaurdar">
                                        <input type="file" name="file" onchange="document.getElementById('imagem').src = window.URL.createObjectURL(this.files[0])" />
                                        <input name="eventoId" hidden value="@ViewData["eventoId"]" />
                                        <input name="curUserId" hidden value="@UserManager.GetUserAsync(User).Result.Id" />
                                        Carregar Foto
                                    </label>&nbsp;
                                    <Button class="btn btn-info botao right" type="Submit" asp-action="AdicionarFoto" asp-controller="Evento" style="color:white;">Adicionar</Button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>